### ISSUE TITLE
Filter build - research topic

### ISSUE THREAD

**Issue by andrewcz** [hoonose/robust-filter#1]
Hi,
Really like this piece of research.
Planning on building on it with a master's project.
I understand it as you calculate the mean and covariance.
So essentially, could I then use these terms to build a more
Robust kalman filter in theory, or in it's current state is it already a state space 
Estimator.
Many thanks,
Best,
Andrew

**Comment by hoonose** [comment]
Hi Andrew,
Thanks for your question! Indeed, in its current state, the code is suited for estimating the mean and covariance of a single Gaussian distribution. In the paper, we also discuss a filter for estimating the mean of distributions with bounded second moments. We have not investigated the domain of Kalman filtering using this technique, and we encourage you to investigate this further if it interests you. We'd love to hear if you find some interesting results!
Sincerely,
Gautam

**Comment by andrewcz** [comment]
Ah im not sure i understand.
A Gaussian is composed of a mean a variance?
A multivariate gaussian has a mean and covariance?
Does that mean it can approximate a multivariate Gaussian distribution? more accurately than current techniques?

Thank you so much for your help.
Best,
Andrew

**Comment by hoonose** [comment]
Hi Andrew,
When I say a Gaussian, I mean a high-dimensional/multivariate Gaussian. There are already effective robust methods for a univariate Gaussian (e.g., the median and interquartile range). To the best of our knowledge, ours is the best method for robustly estimating the mean and covariance of a multivariate Gaussian, where "robustly" in this context is based on the error model described in the paper (very roughly, where an epsilon-fraction of your data comes from something which is not the Gaussian you are trying to estimate).
Gautam

**Comment by andrewcz** [comment]
So, theoretically speaking I could use the estimated mean and covariance to then go a build a Gaussian process model defined by these parameters? Which I would be curious to do.
I was trying to experiment to just use a 2-dimensional case with a large number of points, but I was getting strange values.
How would I change the following line to simulate "tall data" ie 2 dimensions with lots of points?

clear;
eps = 0.05;
tau = 0.1;

sampErr = [];
noisyEmpErr = [];
filterErr = [];
ds = 10:10:50;

%Set to 0 for isotropic covariance
%Set to 1 for spiked covariance

Many thanks for your help, really interesting piece!!
Best,
Andrew

**Comment by hoonose** [comment]
Hi Andrew,

A few comments:
1. In general, I don't think I have the time to keep answering these specific technical questions. The code as provided should be able to reproduce the figures as presented in the paper, but if you want to extend it, you'll have to play around with it more yourself, to see what does and doesn't work -- that's what research is all about! 
2. To answer your specific question, as you can see in line 21, the variable d (for dimension) is chosen from the set of values in the vector ds. You can therefore set the dimension to be 2 just by changing line 8 to be ds = [2];. You would probably also need to change the number of samples: line 22 sets N to be 0.5*d/eps^2. You could try setting this instead to (say) 10*d^2/eps^2, or otherwise however many samples you want/can handle. In high-dimensional settings, we start running into issues of limited memory, but more samples are probably OK in low-dimensional settings.
3. The benefits of our algorithm are really most effective in high-dimensional settings. It's plausible that more naive methods might be comparably effective in low-dimensional settings. For example, if one were concerned about the mean, methods like geometric median or combining the coordinatewise medians would be effective. It might be worth trying naive methods like this first, to see if they're good enough for your purposes.

Gautam
